import { createConstants } from 'shared/utils/redux-utils'

export default createConstants(
  'AUTH_USER_STARTED',
  'AUTH_USER_COMPLETED',
  'AUTH_USER_FAILED',
  'SHOW_USER_COMPLETED',
  'SHOW_USER_FAILED',
  'REVOKE_USER_COMPLETED',
  'REVOKE_USER_FAILED',
  'SYNC_SERVER_USER_COMPLETED',
  'SYNC_CLIENT_USER_COMPLETED',
  'CHECK_TOKEN_COMPLETED',
  'CHECK_TOKEN_FAILED',
  'LIST_POST_RELOADED',
  'LIST_POST_STARTED',
  'LIST_POST_COMPLETED',
  'LIST_POST_FAILED'
)

