export const SIGNUP_USER_STARTED = 'SIGNUP_USER_STARTED'
export const SIGNUP_USER_COMPLETED = 'SIGNUP_USER_COMPLETED'
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED'

export const AUTH_USER_STARTED = 'AUTH_USER_STARTED'
export const AUTH_USER_COMPLETED = 'AUTH_USER_COMPLETED'
export const AUTH_USER_FAILED = 'AUTH_USER_FAILED'

export const SYNC_SERVER_USER_COMPLETED = 'SYNC_SERVER_USER_COMPLETED'
export const SYNC_CLIENT_USER_COMPLETED = 'SYNC_CLIENT_USER_COMPLETED'

export const REVOKE_USER_STARTED = 'REVOKE_USER_STARTED'
export const REVOKE_USER_COMPLETED = 'REVOKE_USER_COMPLETED'
export const REVOKE_USER_FAILED = 'REVOKE_USER_FAILED'

export const CHANGE_PASS_USER_STARTED = 'CHANGE_PASS_USER_STARTED'
export const CHANGE_PASS_USER_COMPLETED = 'CHANGE_PASS_USER_COMPLETED'
export const CHANGE_PASS_USER_FAILED = 'CHANGE_PASS_USER_FAILED'

export const CREATE_POST_STARTED = 'CREATE_POST_STARTED'
export const CREATE_POST_COMPLETED = 'CREATE_POST_COMPLETED'
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'

export const LIST_POST_STARTED = 'LIST_POST_STARTED'
export const LIST_POST_COMPLETED = 'LIST_POST_COMPLETED'
export const LIST_POST_FAILED = 'LIST_POST_FAILED'

export const SET_PAGE_TITLE_STARTED = 'SET_PAGE_TITLE_STARTED'
export const SET_PAGE_TITLE_COMPLETED = 'SET_PAGE_TITLE_COMPLETED'
export const SET_PAGE_TITLE_FAILED = 'SET_PAGE_TITLE_FAILED'

export const CHECK_TOKEN_COMPLETED = 'CHECK_TOKEN_COMPLETED'
export const CHECK_TOKEN_FAILED = 'CHECK_TOKEN_FAILED'

export const SYNC_SERVER_LOCALE_COMPLETED = 'SYNC_SERVER_LOCALE_COMPLETED'
export const SYNC_CLIENT_LOCALE_COMPLETED = 'SYNC_CLIENT_LOCALE_COMPLETED'

export const UPDATE_TITLE_COMPLETED = 'UPDATE_TITLE_COMPLETED'

export const UPLOAD_FILE_STARTED = 'UPLOAD_FILE_STARTED'
export const UPLOAD_FILE_COMPLETED = 'UPLOAD_FILE_COMPLETED'
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED'
export const UPLOAD_FILE_PROGRESS = 'UPLOAD_FILE_PROGRESS'

export const SET_IMAGE_PREVIEW_COMPLETED = 'SET_IMAGE_PREVIEW_COMPLETED'
export const SET_IMAGE_FILENAME_COMPLETED = 'SET_IMAGE_FILENAME_COMPLETED'
export const CLEAR_UPLOAD_COMPLETED = 'CLEAR_UPLOAD_COMPLETED'
