exports.users = require('./dao/users')
exports.posts = require('./dao/posts')
exports.usersInfo = require('./dao/usersInfo')
exports.admins = require('./dao/admins')
exports.promotions = require('./dao/promotions')
exports.statistics = require('./dao/statistics')
exports.locations = require('./dao/locations')
